# Generated by Django 4.2.16 on 2024-12-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0003_rename_album_id_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songgenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='songgenre',
            old_name='song_id',
            new_name='song',
        ),
    ]
