# Generated by Django 4.2.16 on 2024-12-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0004_rename_genre_id_songgenre_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
